spring:
  application:
    name: scheduler

# Spring Boot Actuator "/health" endpoint configuration (Mostra dettagli aggiuntivi quando si ispeziona /health endpoint)
management:
  endpoint:
    health:
      show-details: always

# Spring Boot Actuator /info endpoint configuration (Informazioni customizzate da visualizzare quanto di ispeziona /info endpoint)
info:
  app:
    name: Scheduler Service
    description: Microservizio che si occupa di effettuare il caricamento dei dati nei DB!

server:
  port: 8082

---
spring:
  profiles: compose

---
spring:
  profiles: kub

security:
  require-ssl: false