version: '3'
services:

  gateway:
    image: marcoscaletta/zuul-service:1.0.0-SNAPSHOT
    container_name: gateway
    environment:
      SPRING_PROFILES_ACTIVE: "compose"
    ports:
      - 8080:8080
  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - '~/Scrivania/inputCassandra:/var/lib/cassandra'

  cassandra-api:
    image: "marcoscaletta/cassandra-api-service:1.0.0-SNAPSHOT"
    container_name: cassandra-api
    environment:
      SPRING_PROFILES_ACTIVE: "compose"
    ports:
      - 8085:8080